### ISSUE TITLE
Lỗi login lần đầu

### ISSUE THREAD

**Issue by bachvtuan** [duythien0912/flutter_zalo_login#14]
Chào bạn, mình thỉnh thoảng gặp trường hợp là login zalo lần đầu và mình phải gọi lại lần 2 .
Code
``
ZaloLoginResult res = await ZaloLogin().logIn();
``
Line code này không trả về kết quả, nhưng ở lần 2 thì ok.
Mình cũng thử ZaloLogin().logIn().catchError nhưng cũng không trả về ở đây.

Lỗi xuất hiện là 
```
W/System.err( 2152): org.json.JSONException: Value com.zing.zalo.devicetrackingsdk.model.PreloadInfo@3175241 of type java.lang.String cannot be converted to JSONObject
W/System.err( 2152): 	at org.json.JSON.typeMismatch(JSON.java:112)
W/System.err( 2152): 	at org.json.JSONObject.<init>(JSONObject.java:168)
W/System.err( 2152): 	at org.json.JSONObject.<init>(JSONObject.java:181)
W/System.err( 2152): 	at com.zing.zalo.zalosdk.core.helper.DeviceHelper.getPreloadInfo(Unknown Source:305)
W/System.err( 2152): 	at com.zing.zalo.devicetrackingsdk.Api.prepareTrackingData(Unknown Source:95)
W/System.err( 2152): 	at com.zing.zalo.devicetrackingsdk.DeviceTracking.prepareTrackingData(Unknown Source:54)
W/System.err( 2152): 	at com.zing.zalo.zalosdk.auth.internal.a.a(Unknown Source:62)
W/System.err( 2152): 	at com.zing.zalo.zalosdk.auth.internal.a$a.a(Unknown Source:1022)
W/System.err( 2152): 	at com.zing.zalo.zalosdk.auth.internal.a$a.doInBackground(Unknown Source:169)
W/System.err( 2152): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err( 2152): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 2152): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err( 2152): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 2152): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 2152): 	at java.lang.Thread.run(Thread.java:919)
2
E/SpannableStringBuilder( 2152): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/ConnectionTracker( 2152): Exception thrown while unbinding
W/ConnectionTracker( 2152): java.lang.IllegalArgumentException: Service not registered: ls@88b3f47
W/ConnectionTracker( 2152): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
W/ConnectionTracker( 2152): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1786)
W/ConnectionTracker( 2152): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
W/ConnectionTracker( 2152): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):1)
W/ConnectionTracker( 2152): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):2)
W/ConnectionTracker( 2152): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):9)
W/ConnectionTracker( 2152): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):3)
W/ConnectionTracker( 2152): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):3)
W/ConnectionTracker( 2152): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker( 2152): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 2152): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204713081@20.47.13 (120400-0):5)

```

**Comment by bachvtuan** [comment]
Mình phát hiện được lỗi là do trong lúc mình init zalo thì mình cũng thực hiện 1 future khác nhưng future khác fail nên dẫn đến lỗi luôn. cách giải quyết là đợi init zalo xong thì mình mới gọi hàm future kia .
